# Generated by Django 4.1.5 on 2023-01-14 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pincode', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('pincode', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='road',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('length', models.PositiveIntegerField()),
                ('lanes', models.PositiveIntegerField()),
                ('speed_limit', models.PositiveIntegerField()),
                ('street_type', models.CharField(choices=[('One Way', 'One Way'), ('Two Way', 'Two Way')], max_length=255)),
                ('area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.area')),
            ],
        ),
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='city_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.city'),
        ),
        migrations.CreateModel(
            name='accidents_reported',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('Rear-end collision', 'Rear-end collision'), ('Side-impact collision', 'Side-impact collision'), ('Rollover', 'Rollover'), ('Head on collisions', 'Head on collisions')], max_length=255)),
                ('death_rate', models.PositiveIntegerField()),
                ('area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.area')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='accidents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=255)),
                ('accident_type', models.CharField(choices=[('Rear-end collision', 'Rear-end collision'), ('Side-impact collision', 'Side-impact collision'), ('Rollover', 'Rollover'), ('Head on collisions', 'Head on collisions')], max_length=255)),
                ('age_group', models.CharField(choices=[('0-10', '0-10'), ('11-20', '11-20'), ('21-30', '21-30'), ('31-40', '31-40'), ('40-60', '40-60'), ('60+', '60+')], max_length=255)),
                ('road_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.area')),
            ],
        ),
    ]
