# Generated by Django 4.1.5 on 2023-01-18 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='area_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.area'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaint',
            name='city_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.city'),
            preserve_default=False,
        ),
    ]
