# Generated by Django 4.1.5 on 2023-01-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_complaint_area_id_complaint_city_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='accidents',
            name='NUmber_of_Accidents',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
