# Generated by Django 4.1.5 on 2023-01-24 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_accidents_number_of_accidents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accidents',
            old_name='NUmber_of_Accidents',
            new_name='Number_of_Accidents',
        ),
    ]
