# Generated by Django 4.1.5 on 2023-01-30 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_number_of_accidents_accidents_number_of_accidents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accidents_reported',
            old_name='vehicle_type',
            new_name='accident_type',
        ),
        migrations.AlterField(
            model_name='road',
            name='length',
            field=models.DecimalField(decimal_places=5, max_digits=10, max_length=2),
        ),
    ]
