# Generated by Django 4.1.5 on 2023-01-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_vehicle_type_accidents_reported_accident_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='road',
            name='length',
            field=models.DecimalField(decimal_places=2, max_digits=5, max_length=4),
        ),
    ]
