# Generated by Django 4.1.5 on 2023-01-30 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_road_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='road',
            name='length',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
