# Generated by Django 4.1.5 on 2023-01-31 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_complaint_cityname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='cityname',
        ),
    ]
